testPeriodYears = 2021:2070;

load 32c.mat

grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '32C wet bulb exceedences', ...
                  'fileTitle', 'exceedences-32c.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);



load 33c.mat

grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '33C wet bulb exceedences', ...
                  'fileTitle', 'exceedences-33c.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);