testPeriodYears = 2021:2070;

load 30c-ssp3-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '30C, SSP3 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-30c-ssp3.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);





load 30c-ssp5-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '30C, SSP5 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-30c-ssp5.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);





load 31c-ssp3-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '31C, SSP3 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-31c-ssp3.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);





load 31c-ssp5-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '31C, SSP5 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-31c-ssp5.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);




load 32c-ssp3-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '32C, SSP3 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-32c-ssp3.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);





load 32c-ssp5-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '32C, SSP5 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-32c-ssp5.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);





load 33c-ssp3-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '33C, SSP3 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-33c-ssp3.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);






load 33c-ssp5-grid.mat
grid = nanmean(squeeze(nansum(futureSelGrid{3}, 3)), 3) / length(testPeriodYears);
grid(grid == 0) = NaN;
result = {futureSelGrid{1}, futureSelGrid{2}, grid};

saveData = struct('data', {result}, ...
                  'plotRegion', 'asia-heat', ...
                  'plotRange', [0 0.5], ...
                  'plotTitle', '33C, SSP5 wet bulb exceedences', ...
                  'fileTitle', 'exceedences-33c-ssp5.pdf', ...
                  'plotXUnits', 'Days/year', ...
                  'blockWater', false);
plotFromDataFile(saveData);
