% extreme change - mean change

percentile = 'mean';

load(['tasmaxChange-all-rcp-multi-model-extreme-' percentile '-2070-2080.mat']);
tasmaxExtChg = saveData.data;

load(['tasmaxChange-all-rcp-multi-model-mean-' percentile '-2070-2080.mat']);
tasmaxMeanChg = saveData.data;

tasmaxDiff = tasmaxExtChg{3} - tasmaxMeanChg{3};

plotTitle = 'Temperature';
fileTitle = ['meanVsExt-tasmax-' percentile '-2070-2080.pdf'];
result = {tasmaxExtChg{1}, tasmaxExtChg{2}, tasmaxDiff};
saveData = struct('data', {result}, ...
                  'plotRegion', 'world', ...
                  'plotRange', [-3 3], ...
                  'plotTitle', plotTitle, ...
                  'fileTitle', fileTitle, ...
                  'plotXUnits', 'Degrees C', ...
                  'plotCountries', false, ...
                  'plotStates', false, ...
                  'blockWater', true);
plotFromDataFile(saveData);





load(['wbChange-all-rcp-multi-model-extreme-' percentile '-2070-2080.mat']);
wbExtChg = saveData.data;

load(['wbChange-all-rcp-multi-model-mean-' percentile '-2070-2080.mat']);
wbMeanChg = saveData.data;

wbDiff = wbExtChg{3} - wbMeanChg{3};

plotTitle = 'Wet bulb temperature';
fileTitle = ['meanVsExt-wb-' percentile '-2070-2080.pdf'];
result = {wbExtChg{1}, wbExtChg{2}, wbDiff};
saveData = struct('data', {result}, ...
                  'plotRegion', 'world', ...
                  'plotRange', [-3 3], ...
                  'plotTitle', plotTitle, ...
                  'fileTitle', fileTitle, ...
                  'plotXUnits', 'Degrees C', ...
                  'plotCountries', false, ...
                  'plotStates', false, ...
                  'blockWater', true);
plotFromDataFile(saveData);