robocopy e:\data\cmip5\output\access1-0\mon d:\data\cmip5\output\access1-0\mon /MIR
robocopy e:\data\cmip5\output\access1-3\mon d:\data\cmip5\output\access1-3\mon /MIR
robocopy e:\data\cmip5\output\bcc-csm1-1-m\mon d:\data\cmip5\output\bcc-csm1-1-m\mon /MIR
robocopy e:\data\cmip5\output\bnu-esm\mon d:\data\cmip5\output\bnu-esm\mon /MIR
robocopy e:\data\cmip5\output\canesm2\mon d:\data\cmip5\output\canesm2\mon /MIR
robocopy e:\data\cmip5\output\ccsm4\mon d:\data\cmip5\output\ccsm4\mon /MIR
robocopy e:\data\cmip5\output\cesm1-bgc\mon d:\data\cmip5\output\cesm1-bgc\mon /MIR
robocopy e:\data\cmip5\output\cesm1-cam5\mon d:\data\cmip5\output\cesm1-cam5\mon /MIR
robocopy e:\data\cmip5\output\cmcc-cm\mon d:\data\cmip5\output\cmcc-cm\mon /MIR
robocopy e:\data\cmip5\output\cmcc-cms\mon d:\data\cmip5\output\cmcc-cms\mon /MIR
robocopy e:\data\cmip5\output\cnrm-cm5\mon d:\data\cmip5\output\cnrm-cm5\mon /MIR
robocopy e:\data\cmip5\output\csiro-mk3-6-0\mon d:\data\cmip5\output\csiro-mk3-6-0\mon /MIR
robocopy e:\data\cmip5\output\fgoals-g2\mon d:\data\cmip5\output\fgoals-g2\mon /MIR
robocopy e:\data\cmip5\output\gfdl-esm2g\mon d:\data\cmip5\output\gfdl-esm2g\mon /MIR
robocopy e:\data\cmip5\output\gfdl-esm2m\mon d:\data\cmip5\output\gfdl-esm2m\mon /MIR
robocopy e:\data\cmip5\output\hadgem2-cc\mon d:\data\cmip5\output\hadgem2-cc\mon /MIR
robocopy e:\data\cmip5\output\hadgem2-es\mon d:\data\cmip5\output\hadgem2-es\mon /MIR
robocopy e:\data\cmip5\output\inmcm4\mon d:\data\cmip5\output\inmcm4\mon /MIR
robocopy e:\data\cmip5\output\miroc5\mon d:\data\cmip5\output\miroc5\mon /MIR
robocopy e:\data\cmip5\output\miroc-esm\mon d:\data\cmip5\output\miroc-esm\mon /MIR
robocopy e:\data\cmip5\output\mpi-esm-mr\mon d:\data\cmip5\output\mpi-esm-mr\mon /MIR
robocopy e:\data\cmip5\output\mri-cgcm3\mon d:\data\cmip5\output\mri-cgcm3\mon /MIR
robocopy e:\data\cmip5\output\noresm1-m\mon d:\data\cmip5\output\noresm1-m\mon /MIR