
dataset = 'cmip5';
models = {'access1-0', 'access1-3', 'bcc-csm1-1-m', 'bnu-esm', 'canesm2', ...
               'cmcc-cm', 'cmcc-cms', 'cmcc-cesm', 'cnrm-cm5', 'csiro-mk3-6-0', ...
              'fgoals-g2', 'gfdl-esm2g', 'gfdl-esm2m', 'hadgem2-cc', ...
              'hadgem2-es', 'inmcm4', 'ipsl-cm5a-mr', 'miroc5', 'miroc-esm', ...
              'mpi-esm-mr', 'mri-cgcm3', 'noresm1-m'};
var = 'ef';          

load lat;
load lon;

load waterGrid;
waterGrid = logical(waterGrid);

load('2017-bowen/hottest-season-txx-rel-cmip5-all-txx.mat');
groups = [];

for m = 1:length(models)
    load(['e:/data/projects/bowen/derived-chg/var-stats/efGroup-' models{m} '.mat']);
    efGroup(waterGrid) = NaN;
    groups(:,:,m) = efGroup;
end

result = {lat,lon,mode(groups,3)};
    
saveData = struct('data', {result}, ...
                  'plotRegion', 'world', ...
                  'plotRange', [1 4], ...
                  'cbXTicks', [], ...
                  'plotTitle', [''], ...
                  'fileTitle', ['ef-groups.eps'], ...
                  'plotXUnits', [''], ...
                  'blockWater', true, ...
                  'colormap', brewermap(4, 'BrBG'));

plotFromDataFile(saveData);

