load hottest-season-txx-rel-cmip5.mat
load lat
load lon

models = {'access1-0', 'access1-3', 'bcc-csm1-1-m', 'bnu-esm', 'canesm2', ...
              'ccsm4', 'cesm1-bgc', 'cesm1-cam5', 'cmcc-cm', 'cmcc-cms', 'cmcc-cesm', 'cnrm-cm5', 'csiro-mk3-6-0', ...
              'fgoals-g2', 'gfdl-esm2g', 'gfdl-esm2m', 'hadgem2-cc', ...
              'hadgem2-es', 'inmcm4', 'ipsl-cm5a-mr', 'miroc5', 'miroc-esm', ...
              'mpi-esm-mr', 'mri-cgcm3', 'noresm1-m'};
          
for m = 1:length(models)

result = {lat, lon, hottestSeason(:,:,m)};

saveData = struct('data', {result}, ...
                  'plotRegion', 'world', ...
                  'plotRange', [1 12], ...
                  'cbXTicks', 1:12, ...
                  'plotTitle', [models{m} ' TXx month'], ...
                  'fileTitle', ['hottest-season-' models{m} '.png'], ...
                  'plotXUnits', ['Month'], ...
                  'blockWater', false, ...
                  'colormap', brewermap(11,'*Spectral'));
plotFromDataFile(saveData);
end
    