
vars = {'tasmax', 'tasmin', 'mrso', 'zg500', 'swe', 'ua', 'va', 'hus', 'pr', 'ta', 'psl'};

models = {'narccap/raw/crcm/ccsm', 'narccap/raw/crcm/cgcm3', ...
        'narccap/raw/ecp2/gfdl', 'narccap/raw/hrm3/gfdl', ...
        'narccap/raw/hrm3/hadcm3', 'narccap/raw/mm5i/ccsm', ...
        'narccap/raw/mm5i/hadcm3', 'narccap/raw/rcm3/cgcm3', ...
        'narccap/raw/rcm3/gfdl', 'narccap/raw/wrfg/ccsm', ...
        'narccap/raw/wrfg/cgcm3'};

% models = {'narccap/raw/crcm/ncep', 'narccap/raw/ecp2/ncep', ...
%           'narccap/raw/hrm3/ncep', 'narccap/raw/mm5i/ncep', ...
%           'narccap/raw/rcm3/ncep', 'narccap/raw/wrfg/ncep'};

for v = 1:length(vars)
    for m = 1:length(models)
        narccapNcToMat(['e:/data/' models{m} '/' vars{v}], 'e:/data/narccap/output', vars{v}, -1);
    end
end